[project]
name = "fuzhouhua"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "paddle2onnx==1.3.1",
    "pytubefix>=8.12.2",
    "tqdm>=4.67.1",
]
